interface ImportMetaEnv {
	/**
	 * The refresh token is used to receive a new access token without the authentication procedure.
	 */
	readonly REFRESH_TOKEN: string;

	/**
	 * The authentication code is the Base64-encoded value of `client_id:client_secret`.
	 * It is necessary for getting a new access token using the `refreshToken`.
	 */
	readonly AUTHENTICATION_CODE: Base64URLString;

	/**
	 * The Turso database URL.
	 */
	readonly ASTRO_DB_REMOTE_URL: string;

	/**
	 * The JSON Web Token (JWT) for database access.
	 * Generated by Turso.
	 */
	readonly ASTRO_DB_APP_TOKEN: string;
}

interface ImportMeta {
	readonly env: ImportMetaEnv;
}